DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;

DROP INDEX IF EXISTS idx_user_username CASCADE;
DROP INDEX IF EXISTS idx_inventory_user CASCADE;
DROP INDEX IF EXISTS idx_inventory_item CASCADE;
DROP INDEX IF EXISTS idx_transactions_from CASCADE;
DROP INDEX IF EXISTS idx_transactions_to CASCADE;