serviceName: "svc-name"
secret: "DYHlaJpPiZ"

server:
  mode: "test"
  port: 8080
  scheme: "http"
  domain: "localhost"

db:
  host: "localhost"
  port: 5432
  user: "app_user"
  password: "superstrongpassword"
  database: "app_test"

jaeger:
  sampler:
    type: "const"
    param: 1
  reporter:
    LogSpans: true
    LocalAgentHostPort: "localhost:6831"